### ISSUE TITLE
why don't you use styles to decorate component

### ISSUE THREAD

**Issue by FailLone** [mightyiam/cyclejs-web-components#25]
This project is really wonderful, but protosomatic components are simple and ugly.
so, how about decorate them? like ant-design

**Comment by mightyiam** [comment]
Thank you for contacting.

I couldn't find out what protosomatic means.

Firstly, this is in very early stages.

Now, to the point.

I was pleased to find http://bulma.io/, a CSS framework that has zero JavaScript. I like the idea.

I would like to do the same. This is a framework-specific component framework. Zero CSS.

Cool?

Closing this but you're welcome to continue the conversation.
